### ISSUE TITLE
Provide bundled dependencies?

### ISSUE THREAD

**Issue by KonH** [utkaka/UnityBuildVariants#2]
Hello!
I have noticed that the project currently isn't easy to check out.
To use it inside Unity project additional actions are required from a user like adding third-party dependencies manually.
I understand that you can except that project will be built into a library and then placed inside Plugins directory of a project. But for my experience, it's hard for ordinary Unity developer.
The much easiest way to handle it - bundle dependencies inside the project (it's lead to little harder maintain in future, of course).
I made a branch with it - https://github.com/KonH/UnityBuildVariants/tree/bundled_dependencies. If you want, I can submit a pull request.

**Comment by utkaka** [comment]
Thanks for feedback! I made release with complete unitypackage, so everyone can just download it and import to their project. I think it is the best choice.
